"""Add first_name and last_name (nullable)

Revision ID: 745a639f5ce5
Revises: 15f8013d935f
Create Date: 2025-05-05 16:22:52.535485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745a639f5ce5'
down_revision = '15f8013d935f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_timestamp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
